server:
  port: 8081
spring:
  application:
    name: cloud-item-service
  datasource:
    url: jdbc:mysql:///youshop
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    virtual-host: youshop
    username: youshop
    password: youshop
    host: 192.168.142.128
    port: 5672
    template:
      exchange: youshop.item.exchange  # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5          # 心跳时间
    lease-expiration-duration-in-seconds: 15      # 在15s内没有心跳则驱逐
mybatis:
  type-aliases-package: com.youmei.item.pojo
