server:
  port: 8087
spring:
  application:
    name: cloud-auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
youshop:
  jwt:
    secret: youshop*youmei&springcloud__! # 登录校验的密钥
    pubKeyPath: H:\\rsa\\rsa.pub # 公钥地址
    priKeyPath: H:\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: youshop_token