server:
  port: 8083
spring:
  application:
    name: cloud-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.142.128:9300
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
