server:
  port: 8084
spring:
  application:
    name: cloud-goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: youshop
    host: 192.168.142.128
    username: youshop
    password: youshop
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期